'use strict';
import $ from "jquery";
var Cookies = require('./vendor/js-cookie'); // Node.js: Load js-cookie.js
import { CookiePrompter, PiwikProTracker, CookieMgr } from "./vendor/CookiePrompter";
import * as DKFDS from "dkfds";

require('./sidenav'); // Node.js: Load sidenav.js
require('./scroll-top');
require('./copy-code-button');
document.addEventListener("DOMContentLoaded", function () {

    // If this is a page with a back-to-top button example, ensure that only the 'real' back-to-top button's JavaScript works
    // Without this code, the back-to-top button example would not be visible due to the JavaScript hiding it
    let bodytag = document.getElementsByTagName('body')[0];
    if (bodytag.classList.contains('page-tilbage-til-toppen') || bodytag.classList.contains('page-back-to-top')) {
        let backtotopbuttons = document.getElementsByClassName('back-to-top-button');
        if (backtotopbuttons.length === 2) {
            new DKFDS.BackToTop(backtotopbuttons[1]).init();
        }
        new DKFDS.Navigation().init(); // Only other relevant JavaScript on back-to-top pages is navigation
    }
    // If this is not a back-to-top example page or a test page, init all JavaScript
    else if (!bodytag.classList.contains('layout-test-example')) {
        DKFDS.init();
    }

    let searchForm = document.getElementById('search-form');
    if (searchForm !== null) {
        let form = searchForm.getElementsByTagName('form')[0];
        form.addEventListener('submit', function (e) {
            if (document.getElementById('search-input').value === "") {
                e.preventDefault();
                return false;
            } else {
                return true;
            }
        }, false);
    }

    if (document.getElementsByClassName('component-preview-error-summary-page').length > 0) {
        new DKFDS.ErrorSummary(document.getElementsByClassName('component-preview-error-summary-page')[0].querySelector('.alert[data-module="error-summary"]')).init();
    }

    /* Ensure all pre tags generated by Jekyll can be scrolled with the keyboard */
    let preTags = document.querySelectorAll('figure.highlight pre');
    for (let i = 0; i < preTags.length; i++) {
        preTags[i].setAttribute('tabindex', 0);
    }
});

/* Particularly Firefox has problems viewing the right part of the page when
   an anchor link has been clicked. This eventListener ensures that the
   correct element is displayed in view. */
window.addEventListener("load", (event) => {
    if (location.hash !== '') {
        let elementID = location.hash.replace('#', '');
        let element = document.getElementById(elementID);
        if (element) {
            element.scrollIntoView(true);
        }
    }
});

$(document).ready(function () {
    var onPrivacyPage = document.getElementsByClassName('page-privatlivspolitik-og-cookies').length !== 0;

    CookiePrompter.init({
        trackers: [{
            name: PiwikProTracker,
            config: {
                account: 'e1985634-0fc1-4992-baf6-59088ee23b2a',
                piwikProPath: 'erst.containers.piwik.pro'
            }
        }],
        suppressPrompt: onPrivacyPage
    });

    $('.layout-demo form').submit(function (e) {
        e.preventDefault();
        window.location.href = window.location.origin + $(this).attr('action');
    });

    /*
     * If the user is on the page "privatlivspolitik", show the correct cookie message.
     */
    if (onPrivacyPage) {

        var acceptBtn = document.getElementById('cookieCardAccept');
        var rejectBtn = document.getElementById('cookieCardReject');
        var acceptedMessage = document.querySelector('#cookieCardStatus .accepted');
        var rejectedMessage = document.querySelector('#cookieCardStatus .rejected');

        var showState = function (state) {
            if (state === 'accepted') {
                acceptedMessage.classList.remove('d-none');
                rejectedMessage.classList.add('d-none');
                acceptBtn.classList.add('d-none');
                rejectBtn.classList.remove('d-none');
            } 
            else if (state === 'rejected') {
                acceptedMessage.classList.add('d-none');
                rejectedMessage.classList.remove('d-none');
                acceptBtn.classList.remove('d-none');
                rejectBtn.classList.add('d-none');
            } 
            else if (state === 'no-decision') {
                acceptedMessage.classList.add('d-none');
                rejectedMessage.classList.add('d-none');
                acceptBtn.classList.remove('d-none');
                rejectBtn.classList.remove('d-none');
            }
        };

        var announceStateChange = function (state) {
            var message = state === 'accepted' ? acceptedMessage : rejectedMessage;
            var ariaLiveArea = document.getElementById('aria-live-area');
            if (message && ariaLiveArea) {
                ariaLiveArea.textContent = message.textContent;
            }
        };

        var currentCookieChoice = CookieMgr.readCookie('cookieOptOut');
        if (currentCookieChoice === 'y') {
            showState('accepted');
        } 
        else if (currentCookieChoice === 'n') {
            showState('rejected');
        } 
        else {
            showState('no-decision');
        }

        acceptBtn.addEventListener('click', function () {
            CookieMgr.createCookie('cookieOptOut', 'y', 365);
            showState('accepted');
            announceStateChange('accepted');
            rejectBtn.focus();
        });

        rejectBtn.addEventListener('click', function () {
            CookiePrompter.eraseCookiesAndRemovePrompt();
            showState('rejected');
            announceStateChange('rejected');
            acceptBtn.focus();
        });
    }

    var inFormOrLink = false;
    $('.layout-demo a, .layout-demo button').click(function (e) {
        inFormOrLink = true;

        if ($(this).hasClass('alert-leave')) {
            var r = confirm("Du er ved at forlade selvbetjeningsløsningen. Data, der ikke er gemt vil gå tabt. Vil du fortsætte?");
            if (r == true) {
                inFormOrLink = true;
                return true;
            } else {
                e.preventDefault();
                inFormOrLink = false;
                return false;
            }
        }

        if ($(this).hasClass('alert-leave2')) {
            var r = confirm("Du er ved at forlade siden. Evt. indtastninger der ikke er gemt vil gå tabt. Vil du fortsætte?");
            if (r == true) {
                inFormOrLink = true;
                return true;
            } else {
                e.preventDefault();
                inFormOrLink = false;
                return false;
            }
        }
    });

    $('.layout-iframed .icon-link, .layout-demo .icon-link').click(function (e) {
        var r = confirm("Du er ved at forlade selvbetjeningsløsningen. Data, der ikke er gemt vil gå tabt. Vil du fortsætte?");
        if (r == true) {
            inFormOrLink = true;
            return true;
        } else {
            e.preventDefault();
            inFormOrLink = false;
            return false;
        }
    });

    // alert upon closing page
    window.onbeforeunload = function (e) {
        // do not show popup if destination is within the same solution flow
        if (document.getElementsByClassName('layout-demo').length > 0 && window.themeChangeProcess === undefined) {
            var showPopup = true;
            if (document.activeElement.href !== null && document.activeElement.href !== undefined && window.location.href !== null && window.location.href !== undefined) {
                var targetUrl = document.activeElement.href.split('/');
                var currentUrl = window.location.href.split('/');
                if (targetUrl.length != 0) {
                    if (targetUrl[5] == currentUrl[5]) {
                        showPopup = false;
                    }
                }
            }
            if (showPopup) {
                if (!inFormOrLink) {
                    e = e || window.event;
                    // For IE and Firefox prior to version 4
                    if (e) {
                        e.returnValue = 'Sure?';
                    }
                    // For Safari
                    return 'Sure?';
                }
            }
        }
    };
});
