'use strict';
import $ from "jquery";
var Cookies = require('./vendor/js-cookie'); // Node.js: Load js-cookie.js
import { CookiePrompter, PiwikProTracker, CookieMgr } from "./vendor/CookiePrompter";
import * as DKFDS from "dkfds";

require('./sidenav'); // Node.js: Load sidenav.js
require('./scroll-top');
require('./copy-code-button');
document.addEventListener("DOMContentLoaded", function () {

    // If this is a page with a back-to-top button example, ensure that only the 'real' back-to-top button's JavaScript works
    // Without this code, the back-to-top button example would not be visible due to the JavaScript hiding it
    let bodytag = document.getElementsByTagName('body')[0];
    if (bodytag.classList.contains('page-tilbage-til-toppen') || bodytag.classList.contains('page-back-to-top')) {
        let backtotopbuttons = document.getElementsByClassName('back-to-top-button');
        if (backtotopbuttons.length === 2) {
            new DKFDS.BackToTop(backtotopbuttons[1]).init();
        }
        new DKFDS.Navigation().init(); // Only other relevant JavaScript on back-to-top pages is navigation
    }
    // If this is not a back-to-top example page or a test page, init all JavaScript
    else if (!bodytag.classList.contains('layout-test-example')) {
        DKFDS.init();
    }

    let searchForm = document.getElementById('search-form');
    if (searchForm !== null) {
        let form = searchForm.getElementsByTagName('form')[0];
        form.addEventListener('submit', function (e) {
            if (document.getElementById('search-input').value === "") {
                e.preventDefault();
                return false;
            } else {
                return true;
            }
        }, false);
    }

    if (document.getElementsByClassName('component-preview-error-summary-page').length > 0) {
        new DKFDS.ErrorSummary(document.getElementsByClassName('component-preview-error-summary-page')[0].querySelector('.alert[data-module="error-summary"]')).init();
    }

    /* Ensure all pre tags generated by Jekyll can be scrolled with the keyboard */
    let preTags = document.querySelectorAll('figure.highlight pre');
    for (let i = 0; i < preTags.length; i++) {
        preTags[i].setAttribute('tabindex', 0);
    }
});

/* Particularly Firefox has problems viewing the right part of the page when
   an anchor link has been clicked. This eventListener ensures that the
   correct element is displayed in view. */
window.addEventListener("load", (event) => {
    if (location.hash !== '') {
        let elementID = location.hash.replace('#', '');
        let element = document.getElementById(elementID);
        if (element) {
            element.scrollIntoView(true);
        }
    }
});

$(document).ready(function () {
    CookiePrompter.init({
        trackers: [{
            name: PiwikProTracker,
            config: {
                account: 'e1985634-0fc1-4992-baf6-59088ee23b2a',
                piwikProPath: 'erst.containers.piwik.pro'
            }
        }],
        suppressPrompt: document.getElementsByClassName('page-privatlivspolitik-og-cookies').length !== 0
    });

    $('.layout-demo form').submit(function (e) {
        e.preventDefault();
        window.location.href = window.location.origin + $(this).attr('action');
    });

    /*
     * If the user is on the page "privatlivspolitik", show the correct cookie card.
     */
    if (document.getElementsByClassName('page-privatlivspolitik-og-cookies').length !== 0) {
        var cookieCardNoDecision = document.getElementById('cookieCardNoDecision');
        var cookieCardAccepted = document.getElementById('cookieCardAccepted');
        var cookieCardRejected = document.getElementById('cookieCardRejected');

        var showCard = function (cardToShow) {
            [cookieCardNoDecision, cookieCardAccepted, cookieCardRejected].forEach(function (card) {
                card.parentElement.classList.add('d-none');
            });
            cardToShow.parentElement.classList.remove('d-none');
        };

        var currentCookieChoice = CookieMgr.readCookie('cookieOptOut');
        if (currentCookieChoice === 'y') {
            showCard(cookieCardAccepted);
        }
        else if (currentCookieChoice === 'n') {
            showCard(cookieCardRejected);
        }
        else {
            showCard(cookieCardNoDecision);
        }

        document.getElementById('cookieCardAccept').addEventListener('click', function () {
            CookieMgr.createCookie('cookieOptOut', 'y', 365);
            $('#cookieYesAlert').removeClass('d-none');
            showCard(cookieCardAccepted);
        });

        document.getElementById('cookieCardReject').addEventListener('click', function () {
            CookiePrompter.eraseCookiesAndRemovePrompt();
            $('#cookieNoAlert').removeClass('d-none');
            showCard(cookieCardRejected);
        });

        document.getElementById('cookieCardRejectOnly').addEventListener('click', function () {
            CookiePrompter.eraseCookiesAndRemovePrompt();
            $('#cookieYesAlert').addClass('d-none');
            $('#cookieNoAlert').removeClass('d-none');
            showCard(cookieCardRejected);
        });

        document.getElementById('cookieCardAcceptOnly').addEventListener('click', function () {
            CookieMgr.createCookie('cookieOptOut', 'y', 365);
            $('#cookieNoAlert').addClass('d-none');
            $('#cookieYesAlert').removeClass('d-none');
            showCard(cookieCardAccepted);
        });
    }



    var inFormOrLink = false;
    $('.layout-demo a, .layout-demo button').click(function (e) {
        inFormOrLink = true;

        if ($(this).hasClass('alert-leave')) {
            var r = confirm("Du er ved at forlade selvbetjeningsløsningen. Data, der ikke er gemt vil gå tabt. Vil du fortsætte?");
            if (r == true) {
                inFormOrLink = true;
                return true;
            } else {
                e.preventDefault();
                inFormOrLink = false;
                return false;
            }
        }



        if ($(this).hasClass('alert-leave2')) {
            var r = confirm("Du er ved at forlade siden. Evt. indtastninger der ikke er gemt vil gå tabt. Vil du fortsætte?");
            if (r == true) {
                inFormOrLink = true;
                return true;
            } else {
                e.preventDefault();
                inFormOrLink = false;
                return false;
            }
        }
    });

    $('.layout-iframed .icon-link, .layout-demo .icon-link').click(function (e) {

        var r = confirm("Du er ved at forlade selvbetjeningsløsningen. Data, der ikke er gemt vil gå tabt. Vil du fortsætte?");
        if (r == true) {
            inFormOrLink = true;
            return true;
        } else {
            e.preventDefault();
            inFormOrLink = false;
            return false;
        }

    });

    // alert upon closing page
    window.onbeforeunload = function (e) {
        // do not show popup if destination is within the same solution flow
        if (document.getElementsByClassName('layout-demo').length > 0 && window.themeChangeProcess === undefined) {
            var showPopup = true;
            if (document.activeElement.href !== null && document.activeElement.href !== undefined && window.location.href !== null && window.location.href !== undefined) {
                var targetUrl = document.activeElement.href.split('/');
                var currentUrl = window.location.href.split('/');
                if (targetUrl.length != 0) {
                    if (targetUrl[5] == currentUrl[5]) {
                        showPopup = false;
                    }
                }
            }
            if (showPopup) {
                if (!inFormOrLink) {
                    e = e || window.event;

                    // For IE and Firefox prior to version 4
                    if (e) {
                        e.returnValue = 'Sure?';
                    }

                    // For Safari
                    return 'Sure?';
                }
            }
        }
    };
});


