version: 2
jobs:
  deploy:
    docker:
    - image: circleci/ruby:3.0.0-node-browsers
    steps:
    - checkout
    - run: npm install
    - run: bundle install
    - run: npm run deploy
    - deploy:
        name: Deploy Release to GitHub
        command: |
          bash .circleci/setup-github.sh
workflows:
  version: 2
  build:
    jobs:
    - deploy
